import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'regex-tester',
  route: 'regex-tester',
  category: 'text',
  icon: 'mdi-regex',
  title: { 'zh-TW': '正則表達式測試', en: 'Regex Tester', ja: '正規表現テスター', ko: '정규식 테스터' },
  description: {
    'zh-TW': '即時測試正則表達式，顯示匹配與擷取群組。',
    en: 'Test regular expressions live with matches and capture groups.',
    ja: '正規表現をリアルタイムでテストし、マッチとキャプチャグループを表示します。',
    ko: '정규식을 실시간으로 테스트하고 매치와 캡처 그룹을 표시합니다.',
  },
  keywords: ['regex', 'regexp', 'pattern', 'match', '正則', '正規', '表達式', '正規表現', '정규식'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    pattern: '正則表達式',
    flags: '旗標',
    testString: '測試字串',
    matchCount: '匹配數：{n}',
    noMatch: '沒有匹配。',
    match: '匹配 #{n}',
    indexAt: '位置 {i}',
    groups: '擷取群組',
    group: '群組 {n}',
    namedGroup: '群組「{name}」',
    invalidRegex: '無效的正則表達式：{msg}',
  },
  en: {
    pattern: 'Pattern',
    flags: 'Flags',
    testString: 'Test string',
    matchCount: 'Matches: {n}',
    noMatch: 'No matches.',
    match: 'Match #{n}',
    indexAt: 'at index {i}',
    groups: 'Capture groups',
    group: 'Group {n}',
    namedGroup: 'Group "{name}"',
    invalidRegex: 'Invalid regex: {msg}',
  },
  ja: {
    pattern: '正規表現',
    flags: 'フラグ',
    testString: 'テスト文字列',
    matchCount: 'マッチ数：{n}',
    noMatch: 'マッチなし。',
    match: 'マッチ #{n}',
    indexAt: '位置 {i}',
    groups: 'キャプチャグループ',
    group: 'グループ {n}',
    namedGroup: 'グループ「{name}」',
    invalidRegex: '無効な正規表現：{msg}',
  },
  ko: {
    pattern: '정규식',
    flags: '플래그',
    testString: '테스트 문자열',
    matchCount: '매치 수: {n}',
    noMatch: '매치 없음.',
    match: '매치 #{n}',
    indexAt: '위치 {i}',
    groups: '캡처 그룹',
    group: '그룹 {n}',
    namedGroup: '그룹 "{name}"',
    invalidRegex: '잘못된 정규식: {msg}',
  },
}
