import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'ip-subnet',
  route: 'ip-subnet',
  category: 'dev',
  icon: 'mdi-ip-network',
  title: {
    'zh-TW': 'IP 子網路計算器',
    en: 'IP Subnet Calculator',
    ja: 'IP サブネット計算機',
    ko: 'IP 서브넷 계산기',
  },
  description: {
    'zh-TW': '輸入 IPv4 與 CIDR 前綴，計算網路位址、廣播位址、遮罩與可用主機範圍。',
    en: 'Enter an IPv4 + CIDR prefix to compute network, broadcast, masks and the usable host range.',
    ja: 'IPv4 と CIDR プレフィックスを入力し、ネットワークアドレス・ブロードキャストアドレス・マスク・利用可能なホスト範囲を計算します。',
    ko: 'IPv4 와 CIDR 프리픽스를 입력하여 네트워크 주소, 브로드캐스트 주소, 마스크, 사용 가능한 호스트 범위를 계산합니다.',
  },
  keywords: ['ip', 'subnet', 'cidr', 'netmask', 'network', '子網路', '遮罩', 'サブネット', 'マスク', '서브넷', '마스크'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    ip: 'IP 位址',
    prefix: 'CIDR 前綴',
    cidrHint: '可直接輸入如 192.168.1.10/24',
    network: '網路位址',
    broadcast: '廣播位址',
    netmask: '子網路遮罩',
    wildcard: '萬用遮罩',
    hostRange: '可用主機範圍',
    firstHost: '第一個主機',
    lastHost: '最後一個主機',
    totalHosts: '總位址數',
    usableHosts: '可用主機數',
    ipClass: 'IP 等級',
    errInvalid: '無效的 IPv4 位址或 CIDR 前綴（0–32）。',
  },
  en: {
    ip: 'IP address',
    prefix: 'CIDR prefix',
    cidrHint: 'You can paste e.g. 192.168.1.10/24',
    network: 'Network address',
    broadcast: 'Broadcast address',
    netmask: 'Subnet mask',
    wildcard: 'Wildcard mask',
    hostRange: 'Usable host range',
    firstHost: 'First host',
    lastHost: 'Last host',
    totalHosts: 'Total addresses',
    usableHosts: 'Usable hosts',
    ipClass: 'IP class',
    errInvalid: 'Invalid IPv4 address or CIDR prefix (0–32).',
  },
  ja: {
    ip: 'IP アドレス',
    prefix: 'CIDR プレフィックス',
    cidrHint: '例: 192.168.1.10/24 のように入力できます',
    network: 'ネットワークアドレス',
    broadcast: 'ブロードキャストアドレス',
    netmask: 'サブネットマスク',
    wildcard: 'ワイルドカードマスク',
    hostRange: '利用可能なホスト範囲',
    firstHost: '最初のホスト',
    lastHost: '最後のホスト',
    totalHosts: '総アドレス数',
    usableHosts: '利用可能なホスト数',
    ipClass: 'IP クラス',
    errInvalid: '無効な IPv4 アドレスまたは CIDR プレフィックス（0–32）です。',
  },
  ko: {
    ip: 'IP 주소',
    prefix: 'CIDR 프리픽스',
    cidrHint: '예: 192.168.1.10/24 형식으로 입력할 수 있습니다',
    network: '네트워크 주소',
    broadcast: '브로드캐스트 주소',
    netmask: '서브넷 마스크',
    wildcard: '와일드카드 마스크',
    hostRange: '사용 가능한 호스트 범위',
    firstHost: '첫 번째 호스트',
    lastHost: '마지막 호스트',
    totalHosts: '전체 주소 수',
    usableHosts: '사용 가능한 호스트 수',
    ipClass: 'IP 클래스',
    errInvalid: '유효하지 않은 IPv4 주소 또는 CIDR 프리픽스(0–32)입니다.',
  },
}
