import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'text-sort',
  route: 'text-sort',
  category: 'text',
  icon: 'mdi-sort',
  title: {
    'zh-TW': '文字排序 / 去重',
    en: 'Text Sort / Dedupe',
    ja: 'テキストの並べ替え / 重複削除',
    ko: '텍스트 정렬 / 중복 제거',
  },
  description: {
    'zh-TW': '逐行排序、去除重複、反轉與整理文字。',
    en: 'Sort lines, remove duplicates, reverse and tidy text.',
    ja: '行ごとに並べ替え、重複を削除し、順序を反転してテキストを整理します。',
    ko: '줄 단위로 정렬하고 중복을 제거하며 순서를 반전하여 텍스트를 정리합니다.',
  },
  keywords: ['sort', 'dedupe', 'unique', 'lines', '排序', '去重', '去除重複', '並べ替え', '정렬'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    inputText: '輸入文字（每行一項）',
    sort: '排序',
    none: '不排序',
    asc: '升冪',
    desc: '降冪',
    numeric: '數值排序',
    caseInsensitive: '忽略大小寫',
    removeDuplicates: '移除重複行',
    reverse: '反轉順序',
    trim: '修剪空白',
    removeEmpty: '移除空行',
    linesBefore: '處理前：{n} 行',
    linesAfter: '處理後：{n} 行',
  },
  en: {
    inputText: 'Input text (one item per line)',
    sort: 'Sort',
    none: 'No sort',
    asc: 'Ascending',
    desc: 'Descending',
    numeric: 'Numeric sort',
    caseInsensitive: 'Case-insensitive',
    removeDuplicates: 'Remove duplicates',
    reverse: 'Reverse order',
    trim: 'Trim whitespace',
    removeEmpty: 'Remove empty lines',
    linesBefore: 'Before: {n} lines',
    linesAfter: 'After: {n} lines',
  },
  ja: {
    inputText: 'テキストを入力（1 行に 1 項目）',
    sort: '並べ替え',
    none: '並べ替えなし',
    asc: '昇順',
    desc: '降順',
    numeric: '数値で並べ替え',
    caseInsensitive: '大文字小文字を区別しない',
    removeDuplicates: '重複行を削除',
    reverse: '順序を反転',
    trim: '空白を除去',
    removeEmpty: '空行を削除',
    linesBefore: '処理前：{n} 行',
    linesAfter: '処理後：{n} 行',
  },
  ko: {
    inputText: '텍스트 입력（한 줄에 한 항목）',
    sort: '정렬',
    none: '정렬 안 함',
    asc: '오름차순',
    desc: '내림차순',
    numeric: '숫자 정렬',
    caseInsensitive: '대소문자 구분 안 함',
    removeDuplicates: '중복 줄 제거',
    reverse: '순서 반전',
    trim: '공백 제거',
    removeEmpty: '빈 줄 제거',
    linesBefore: '처리 전: {n} 줄',
    linesAfter: '처리 후: {n} 줄',
  },
}
