import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'bcrypt',
  route: 'bcrypt',
  category: 'encode',
  icon: 'mdi-lock',
  title: { 'zh-TW': 'Bcrypt 雜湊 / 驗證', en: 'Bcrypt Hash / Verify', ja: 'Bcrypt ハッシュ / 検証', ko: 'Bcrypt 해시 / 검증' },
  description: {
    'zh-TW': '產生 bcrypt 雜湊或驗證明文與雜湊是否相符，全程在瀏覽器執行。',
    en: 'Generate a bcrypt hash or verify a plaintext against a hash, entirely in the browser.',
    ja: 'bcrypt ハッシュを生成、または平文とハッシュが一致するか検証します。すべてブラウザー内で実行されます。',
    ko: 'bcrypt 해시를 생성하거나 평문과 해시가 일치하는지 검증하며 모든 처리는 브라우저에서 실행됩니다.',
  },
  keywords: ['bcrypt', 'hash', 'password', 'verify', '雜湊', '密碼', '驗證', 'ハッシュ', '해시'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    hashTab: '產生雜湊',
    verifyTab: '驗證',
    inputText: '輸入文字',
    rounds: '成本 (rounds)',
    hashResult: 'Bcrypt 雜湊',
    generate: '產生',
    plaintext: '明文',
    hashToVerify: 'Bcrypt 雜湊',
    verify: '驗證',
    match: '相符',
    noMatch: '不相符',
    computing: '計算中…',
  },
  en: {
    hashTab: 'Hash',
    verifyTab: 'Verify',
    inputText: 'Input text',
    rounds: 'Cost (rounds)',
    hashResult: 'Bcrypt hash',
    generate: 'Generate',
    plaintext: 'Plaintext',
    hashToVerify: 'Bcrypt hash',
    verify: 'Verify',
    match: 'Match',
    noMatch: 'No match',
    computing: 'Computing…',
  },
  ja: {
    hashTab: 'ハッシュ生成',
    verifyTab: '検証',
    inputText: 'テキストを入力',
    rounds: 'コスト (rounds)',
    hashResult: 'Bcrypt ハッシュ',
    generate: '生成',
    plaintext: '平文',
    hashToVerify: 'Bcrypt ハッシュ',
    verify: '検証',
    match: '一致',
    noMatch: '不一致',
    computing: '計算中…',
  },
  ko: {
    hashTab: '해시 생성',
    verifyTab: '검증',
    inputText: '텍스트 입력',
    rounds: '비용 (rounds)',
    hashResult: 'Bcrypt 해시',
    generate: '생성',
    plaintext: '평문',
    hashToVerify: 'Bcrypt 해시',
    verify: '검증',
    match: '일치',
    noMatch: '불일치',
    computing: '계산 중…',
  },
}
