import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'image-convert',
  route: 'image-convert',
  category: 'media',
  icon: 'mdi-image-sync',
  title: {
    'zh-TW': '圖片格式轉換 / 壓縮',
    en: 'Image Convert / Compress',
    ja: '画像変換 / 圧縮',
    ko: '이미지 변환 / 압축',
  },
  description: {
    'zh-TW': '在 PNG、JPEG、WEBP 之間轉換圖片，並可調整品質與壓縮大小。',
    en: 'Convert images between PNG, JPEG and WEBP, with quality and size compression.',
    ja: 'PNG、JPEG、WEBP 間で画像を変換し、品質やファイルサイズを調整・圧縮できます。',
    ko: 'PNG, JPEG, WEBP 간에 이미지를 변환하고 품질과 압축 크기를 조정할 수 있습니다.',
  },
  keywords: ['image', 'convert', 'compress', 'png', 'jpeg', 'webp', '圖片', '轉換', '壓縮', '画像変換', '圧縮', '이미지 변환', '압축'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    uploadHint: '上傳圖片（PNG / JPEG / WEBP …）',
    targetFormat: '目標格式',
    quality: '品質',
    compress: '額外壓縮（限制最大檔案大小）',
    maxSize: '最大檔案大小 (MB)',
    convert: '轉換',
    converting: '處理中…',
    original: '原始',
    result: '轉換結果',
    dimensions: '尺寸',
    fileSize: '檔案大小',
    download: '下載',
    errLoad: '無法載入圖片。',
    errConvert: '轉換失敗。',
  },
  en: {
    uploadHint: 'Upload an image (PNG / JPEG / WEBP …)',
    targetFormat: 'Target format',
    quality: 'Quality',
    compress: 'Extra compression (limit max file size)',
    maxSize: 'Max file size (MB)',
    convert: 'Convert',
    converting: 'Processing…',
    original: 'Original',
    result: 'Result',
    dimensions: 'Dimensions',
    fileSize: 'File size',
    download: 'Download',
    errLoad: 'Could not load the image.',
    errConvert: 'Conversion failed.',
  },
  ja: {
    uploadHint: '画像をアップロード（PNG / JPEG / WEBP …）',
    targetFormat: '変換後のフォーマット',
    quality: '品質',
    compress: '追加圧縮（最大ファイルサイズを制限）',
    maxSize: '最大ファイルサイズ (MB)',
    convert: '変換',
    converting: '処理中…',
    original: '元の画像',
    result: '変換結果',
    dimensions: 'サイズ',
    fileSize: 'ファイルサイズ',
    download: 'ダウンロード',
    errLoad: '画像を読み込めませんでした。',
    errConvert: '変換に失敗しました。',
  },
  ko: {
    uploadHint: '이미지 업로드 (PNG / JPEG / WEBP …)',
    targetFormat: '대상 포맷',
    quality: '품질',
    compress: '추가 압축 (최대 파일 크기 제한)',
    maxSize: '최대 파일 크기 (MB)',
    convert: '변환',
    converting: '처리 중…',
    original: '원본',
    result: '변환 결과',
    dimensions: '크기',
    fileSize: '파일 크기',
    download: '다운로드',
    errLoad: '이미지를 불러올 수 없습니다.',
    errConvert: '변환에 실패했습니다.',
  },
}
