import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'countdown',
  route: 'countdown',
  category: 'datetime',
  icon: 'mdi-timer-sand',
  order: 2,
  title: { 'zh-TW': '倒數計時器', en: 'Countdown Timer', ja: 'カウントダウンタイマー', ko: '카운트다운 타이머' },
  description: {
    'zh-TW': '倒數到指定的日期時間，或設定時長後啟動倒數計時並在結束時嗶聲提醒。',
    en: 'Count down to a target date/time, or run a duration timer that beeps when it finishes.',
    ja: '指定した日時までカウントダウンしたり、時間を設定して終了時にビープ音で知らせるタイマーを実行します。',
    ko: '지정한 날짜와 시간까지 카운트다운하거나, 시간을 설정해 종료 시 알림음을 울리는 타이머를 실행합니다.',
  },
  keywords: ['countdown', 'timer', 'duration', '倒數', '計時', '時間', 'カウントダウン', '카운트다운'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    modeTarget: '目標時間',
    modeDuration: '時長計時',
    targetDateTime: '目標日期時間',
    reached: '時間到！',
    days: '天',
    hours: '時',
    minutes: '分',
    seconds: '秒',
    setDuration: '設定時長',
    minutesLabel: '分鐘',
    secondsLabel: '秒',
    start: '開始',
    pause: '暫停',
    resume: '繼續',
    reset: '重設',
    finished: '倒數結束',
  },
  en: {
    modeTarget: 'Target time',
    modeDuration: 'Duration timer',
    targetDateTime: 'Target date & time',
    reached: "Time's up!",
    days: 'Days',
    hours: 'Hours',
    minutes: 'Min',
    seconds: 'Sec',
    setDuration: 'Set duration',
    minutesLabel: 'Minutes',
    secondsLabel: 'Seconds',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    reset: 'Reset',
    finished: 'Countdown finished',
  },
  ja: {
    modeTarget: '目標時刻',
    modeDuration: '時間タイマー',
    targetDateTime: '目標の日付と時刻',
    reached: '時間です！',
    days: '日',
    hours: '時',
    minutes: '分',
    seconds: '秒',
    setDuration: '時間を設定',
    minutesLabel: '分',
    secondsLabel: '秒',
    start: '開始',
    pause: '一時停止',
    resume: '再開',
    reset: 'リセット',
    finished: 'カウントダウン終了',
  },
  ko: {
    modeTarget: '목표 시각',
    modeDuration: '시간 타이머',
    targetDateTime: '목표 날짜 및 시간',
    reached: '시간이 다 됐어요!',
    days: '일',
    hours: '시',
    minutes: '분',
    seconds: '초',
    setDuration: '시간 설정',
    minutesLabel: '분',
    secondsLabel: '초',
    start: '시작',
    pause: '일시정지',
    resume: '재개',
    reset: '초기화',
    finished: '카운트다운 종료',
  },
}
