import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'user-agent',
  route: 'user-agent',
  category: 'dev',
  icon: 'mdi-monitor-cellphone',
  title: {
    'zh-TW': 'User-Agent 解析',
    en: 'User-Agent Parser',
    ja: 'User-Agent パーサー',
    ko: 'User-Agent 파서',
  },
  description: {
    'zh-TW': '解析 User-Agent 字串，辨識瀏覽器、引擎、作業系統與裝置。',
    en: 'Parse a User-Agent string to identify browser, engine, OS and device.',
    ja: 'User-Agent 文字列を解析し、ブラウザ・エンジン・OS・デバイスを識別します。',
    ko: 'User-Agent 문자열을 해석하여 브라우저, 엔진, 운영체제, 기기를 식별합니다.',
  },
  keywords: ['user agent', 'ua', 'browser', 'os', 'device', '瀏覽器', '裝置', 'ブラウザ', 'デバイス', '브라우저', '기기'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    input: 'User-Agent 字串',
    useCurrent: '使用目前瀏覽器',
    field: '項目',
    value: '數值',
    browser: '瀏覽器',
    version: '版本',
    engine: '引擎',
    os: '作業系統',
    device: '裝置',
    vendor: '廠商',
    model: '型號',
    type: '類型',
    cpu: 'CPU 架構',
    unknown: '未知',
  },
  en: {
    input: 'User-Agent string',
    useCurrent: 'Use current browser',
    field: 'Field',
    value: 'Value',
    browser: 'Browser',
    version: 'Version',
    engine: 'Engine',
    os: 'OS',
    device: 'Device',
    vendor: 'Vendor',
    model: 'Model',
    type: 'Type',
    cpu: 'CPU architecture',
    unknown: 'Unknown',
  },
  ja: {
    input: 'User-Agent 文字列',
    useCurrent: '現在のブラウザを使用',
    field: '項目',
    value: '値',
    browser: 'ブラウザ',
    version: 'バージョン',
    engine: 'エンジン',
    os: 'OS',
    device: 'デバイス',
    vendor: 'ベンダー',
    model: 'モデル',
    type: '種類',
    cpu: 'CPU アーキテクチャ',
    unknown: '不明',
  },
  ko: {
    input: 'User-Agent 문자열',
    useCurrent: '현재 브라우저 사용',
    field: '항목',
    value: '값',
    browser: '브라우저',
    version: '버전',
    engine: '엔진',
    os: '운영체제',
    device: '기기',
    vendor: '제조사',
    model: '모델',
    type: '유형',
    cpu: 'CPU 아키텍처',
    unknown: '알 수 없음',
  },
}
