import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'password-generator',
  route: 'password-generator',
  category: 'encode',
  icon: 'mdi-form-textbox-password',
  title: { 'zh-TW': '密碼產生器', en: 'Password Generator', ja: 'パスワード生成', ko: '비밀번호 생성기' },
  description: {
    'zh-TW': '使用密碼學安全亂數產生強密碼，可自訂長度與字元類型。',
    en: 'Generate strong passwords with cryptographically secure randomness and custom character sets.',
    ja: '暗号学的に安全な乱数で強力なパスワードを生成します。長さや文字種をカスタマイズできます。',
    ko: '암호학적으로 안전한 난수로 강력한 비밀번호를 생성하며 길이와 문자 종류를 사용자 지정할 수 있습니다.',
  },
  keywords: ['password', 'generator', 'random', 'secure', '密碼', '亂數', '隨機', 'パスワード', '비밀번호'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    length: '長度',
    uppercase: '大寫字母 (A-Z)',
    lowercase: '小寫字母 (a-z)',
    digits: '數字 (0-9)',
    symbols: "符號 (!{'@'}#…)",
    excludeAmbiguous: '排除易混淆字元 (0O1lI)',
    count: '產生數量',
    regenerate: '重新產生',
    strength: '強度',
    entropy: '熵',
    bits: '位元',
    veryWeak: '非常弱',
    weak: '弱',
    fair: '普通',
    strong: '強',
    veryStrong: '非常強',
    noCharset: '請至少選擇一種字元類型',
  },
  en: {
    length: 'Length',
    uppercase: 'Uppercase (A-Z)',
    lowercase: 'Lowercase (a-z)',
    digits: 'Digits (0-9)',
    symbols: "Symbols (!{'@'}#…)",
    excludeAmbiguous: 'Exclude ambiguous (0O1lI)',
    count: 'Count',
    regenerate: 'Regenerate',
    strength: 'Strength',
    entropy: 'Entropy',
    bits: 'bits',
    veryWeak: 'Very weak',
    weak: 'Weak',
    fair: 'Fair',
    strong: 'Strong',
    veryStrong: 'Very strong',
    noCharset: 'Select at least one character type',
  },
  ja: {
    length: '長さ',
    uppercase: '大文字 (A-Z)',
    lowercase: '小文字 (a-z)',
    digits: '数字 (0-9)',
    symbols: "記号 (!{'@'}#…)",
    excludeAmbiguous: '紛らわしい文字を除外 (0O1lI)',
    count: '生成数',
    regenerate: '再生成',
    strength: '強度',
    entropy: 'エントロピー',
    bits: 'ビット',
    veryWeak: '非常に弱い',
    weak: '弱い',
    fair: '普通',
    strong: '強い',
    veryStrong: '非常に強い',
    noCharset: '少なくとも 1 種類の文字を選択してください',
  },
  ko: {
    length: '길이',
    uppercase: '대문자 (A-Z)',
    lowercase: '소문자 (a-z)',
    digits: '숫자 (0-9)',
    symbols: "기호 (!{'@'}#…)",
    excludeAmbiguous: '혼동되는 문자 제외 (0O1lI)',
    count: '생성 수량',
    regenerate: '다시 생성',
    strength: '강도',
    entropy: '엔트로피',
    bits: '비트',
    veryWeak: '매우 약함',
    weak: '약함',
    fair: '보통',
    strong: '강함',
    veryStrong: '매우 강함',
    noCharset: '문자 종류를 하나 이상 선택하세요',
  },
}
