import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'date-calc',
  route: 'date-calc',
  category: 'datetime',
  icon: 'mdi-calendar-arithmetic',
  order: 1,
  title: { 'zh-TW': '日期加減器', en: 'Date Calculator' },
  description: {
    'zh-TW': '在基準日期上加減年月週日時分，或計算兩個日期之間的間隔。',
    en: 'Add or subtract time from a date, or compute the interval between two dates.',
  },
  keywords: ['date', 'calculator', 'diff', 'interval', '日期', '加減', '間隔', '天數'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    modeAdd: '加減',
    modeDiff: '間隔',
    baseDate: '基準日期時間',
    operation: '運算',
    add: '加上',
    subtract: '減去',
    years: '年',
    months: '月',
    weeks: '週',
    days: '天',
    hours: '小時',
    minutes: '分鐘',
    resultDate: '結果日期',
    startDate: '開始日期時間',
    endDate: '結束日期時間',
    invalidRange: '結束日期需晚於開始日期',
    diffDays: '天數',
    diffWeeks: '週數',
    diffFullMonths: '完整月數',
    diffYears: '年數',
    totalHours: '總小時數',
    totalMinutes: '總分鐘數',
    humanized: '人類可讀',
    copyResult: '複製結果',
  },
  en: {
    modeAdd: 'Add / Subtract',
    modeDiff: 'Interval',
    baseDate: 'Base date & time',
    operation: 'Operation',
    add: 'Add',
    subtract: 'Subtract',
    years: 'Years',
    months: 'Months',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    resultDate: 'Result date',
    startDate: 'Start date & time',
    endDate: 'End date & time',
    invalidRange: 'End date must be after start date',
    diffDays: 'Days',
    diffWeeks: 'Weeks',
    diffFullMonths: 'Full months',
    diffYears: 'Years',
    totalHours: 'Total hours',
    totalMinutes: 'Total minutes',
    humanized: 'Humanized',
    copyResult: 'Copy result',
  },
}
