import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'date-calc',
  route: 'date-calc',
  category: 'datetime',
  icon: 'mdi-calendar-arithmetic',
  order: 1,
  title: { 'zh-TW': '日期加減器', en: 'Date Calculator', ja: '日付計算機', ko: '날짜 계산기' },
  description: {
    'zh-TW': '在基準日期上加減年月週日時分，或計算兩個日期之間的間隔。',
    en: 'Add or subtract time from a date, or compute the interval between two dates.',
    ja: '基準日に年・月・週・日・時・分を加減算したり、2つの日付の間隔を計算します。',
    ko: '기준 날짜에 연·월·주·일·시·분을 더하거나 빼고, 두 날짜 사이의 간격을 계산합니다.',
  },
  keywords: ['date', 'calculator', 'diff', 'interval', '日期', '加減', '間隔', '天數', '日付計算', '날짜 계산'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    modeAdd: '加減',
    modeDiff: '間隔',
    baseDate: '基準日期時間',
    operation: '運算',
    add: '加上',
    subtract: '減去',
    years: '年',
    months: '月',
    weeks: '週',
    days: '天',
    hours: '小時',
    minutes: '分鐘',
    resultDate: '結果日期',
    startDate: '開始日期時間',
    endDate: '結束日期時間',
    invalidRange: '結束日期需晚於開始日期',
    diffDays: '天數',
    diffWeeks: '週數',
    diffFullMonths: '完整月數',
    diffYears: '年數',
    totalHours: '總小時數',
    totalMinutes: '總分鐘數',
    humanized: '人類可讀',
    copyResult: '複製結果',
  },
  en: {
    modeAdd: 'Add / Subtract',
    modeDiff: 'Interval',
    baseDate: 'Base date & time',
    operation: 'Operation',
    add: 'Add',
    subtract: 'Subtract',
    years: 'Years',
    months: 'Months',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    resultDate: 'Result date',
    startDate: 'Start date & time',
    endDate: 'End date & time',
    invalidRange: 'End date must be after start date',
    diffDays: 'Days',
    diffWeeks: 'Weeks',
    diffFullMonths: 'Full months',
    diffYears: 'Years',
    totalHours: 'Total hours',
    totalMinutes: 'Total minutes',
    humanized: 'Humanized',
    copyResult: 'Copy result',
  },
  ja: {
    modeAdd: '加算 / 減算',
    modeDiff: '間隔',
    baseDate: '基準の日付と時刻',
    operation: '演算',
    add: '加算',
    subtract: '減算',
    years: '年',
    months: 'か月',
    weeks: '週',
    days: '日',
    hours: '時間',
    minutes: '分',
    resultDate: '結果の日付',
    startDate: '開始の日付と時刻',
    endDate: '終了の日付と時刻',
    invalidRange: '終了日は開始日より後である必要があります',
    diffDays: '日数',
    diffWeeks: '週数',
    diffFullMonths: '完全な月数',
    diffYears: '年数',
    totalHours: '合計時間',
    totalMinutes: '合計分',
    humanized: '読みやすい形式',
    copyResult: '結果をコピー',
  },
  ko: {
    modeAdd: '더하기 / 빼기',
    modeDiff: '간격',
    baseDate: '기준 날짜 및 시간',
    operation: '연산',
    add: '더하기',
    subtract: '빼기',
    years: '년',
    months: '개월',
    weeks: '주',
    days: '일',
    hours: '시간',
    minutes: '분',
    resultDate: '결과 날짜',
    startDate: '시작 날짜 및 시간',
    endDate: '종료 날짜 및 시간',
    invalidRange: '종료 날짜는 시작 날짜보다 이후여야 합니다',
    diffDays: '일수',
    diffWeeks: '주수',
    diffFullMonths: '온전한 개월 수',
    diffYears: '연수',
    totalHours: '총 시간',
    totalMinutes: '총 분',
    humanized: '읽기 쉬운 형식',
    copyResult: '결과 복사',
  },
}
