import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'qrcode-generate',
  route: 'qrcode-generate',
  category: 'generate',
  icon: 'mdi-qrcode',
  order: 1,
  title: { 'zh-TW': 'QR Code 製作', en: 'QR Code Generator' },
  description: {
    'zh-TW': '產生純文字/網址、WiFi、vCard 的 QR Code，可自訂尺寸、容錯等級與顏色並下載 PNG。',
    en: 'Generate QR codes for text/URL, WiFi or vCard with custom size, error-correction and colors. Download as PNG.',
  },
  keywords: ['qr', 'qrcode', 'wifi', 'vcard', '製作', '二維碼', 'generate'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    contentType: '內容類型',
    typeText: '純文字 / 網址',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: '文字或網址',
    ssid: 'WiFi 名稱（SSID）',
    password: '密碼',
    encryption: '加密方式',
    wifiHidden: '隱藏網路',
    name: '姓名',
    phone: '電話',
    email: '電子郵件',
    org: '組織 / 公司',
    options: '選項',
    size: '尺寸（px）',
    ecLevel: '容錯等級',
    fgColor: '前景色',
    bgColor: '背景色',
    downloadPng: '下載 PNG',
    emptyHint: '請輸入內容以產生 QR Code',
    encNone: '無',
  },
  en: {
    contentType: 'Content type',
    typeText: 'Text / URL',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: 'Text or URL',
    ssid: 'WiFi name (SSID)',
    password: 'Password',
    encryption: 'Encryption',
    wifiHidden: 'Hidden network',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    org: 'Organization',
    options: 'Options',
    size: 'Size (px)',
    ecLevel: 'Error correction',
    fgColor: 'Foreground',
    bgColor: 'Background',
    downloadPng: 'Download PNG',
    emptyHint: 'Enter content to generate a QR code',
    encNone: 'None',
  },
}
