import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'qrcode-generate',
  route: 'qrcode-generate',
  category: 'generate',
  icon: 'mdi-qrcode',
  order: 1,
  title: {
    'zh-TW': 'QR Code 製作',
    en: 'QR Code Generator',
    ja: 'QR Code 作成',
    ko: 'QR Code 생성',
  },
  description: {
    'zh-TW': '產生純文字/網址、WiFi、vCard 的 QR Code，可自訂尺寸、容錯等級與顏色並下載 PNG。',
    en: 'Generate QR codes for text/URL, WiFi or vCard with custom size, error-correction and colors. Download as PNG.',
    ja: 'テキスト/URL、WiFi、vCard の QR Code を生成し、サイズ・誤り訂正レベル・色を指定して PNG でダウンロードできます。',
    ko: '텍스트/URL, WiFi, vCard 용 QR Code 를 생성하고 크기, 오류 정정 레벨, 색상을 지정해 PNG 로 다운로드합니다.',
  },
  keywords: ['qr', 'qrcode', 'wifi', 'vcard', '製作', '二維碼', 'generate', 'QR Code 作成', 'QR Code 생성'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    contentType: '內容類型',
    typeText: '純文字 / 網址',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: '文字或網址',
    ssid: 'WiFi 名稱（SSID）',
    password: '密碼',
    encryption: '加密方式',
    wifiHidden: '隱藏網路',
    name: '姓名',
    phone: '電話',
    email: '電子郵件',
    org: '組織 / 公司',
    options: '選項',
    size: '尺寸（px）',
    ecLevel: '容錯等級',
    fgColor: '前景色',
    bgColor: '背景色',
    downloadPng: '下載 PNG',
    emptyHint: '請輸入內容以產生 QR Code',
    encNone: '無',
  },
  en: {
    contentType: 'Content type',
    typeText: 'Text / URL',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: 'Text or URL',
    ssid: 'WiFi name (SSID)',
    password: 'Password',
    encryption: 'Encryption',
    wifiHidden: 'Hidden network',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    org: 'Organization',
    options: 'Options',
    size: 'Size (px)',
    ecLevel: 'Error correction',
    fgColor: 'Foreground',
    bgColor: 'Background',
    downloadPng: 'Download PNG',
    emptyHint: 'Enter content to generate a QR code',
    encNone: 'None',
  },
  ja: {
    contentType: 'コンテンツの種類',
    typeText: 'テキスト / URL',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: 'テキストまたは URL',
    ssid: 'WiFi 名（SSID）',
    password: 'パスワード',
    encryption: '暗号化方式',
    wifiHidden: 'ステルスネットワーク',
    name: '氏名',
    phone: '電話番号',
    email: 'メールアドレス',
    org: '組織 / 会社',
    options: 'オプション',
    size: 'サイズ（px）',
    ecLevel: '誤り訂正レベル',
    fgColor: '前景色',
    bgColor: '背景色',
    downloadPng: 'PNG をダウンロード',
    emptyHint: 'QR Code を生成する内容を入力してください',
    encNone: 'なし',
  },
  ko: {
    contentType: '콘텐츠 유형',
    typeText: '텍스트 / URL',
    typeWifi: 'WiFi',
    typeVcard: 'vCard',
    text: '텍스트 또는 URL',
    ssid: 'WiFi 이름（SSID）',
    password: '비밀번호',
    encryption: '암호화 방식',
    wifiHidden: '숨겨진 네트워크',
    name: '이름',
    phone: '전화번호',
    email: '이메일',
    org: '조직 / 회사',
    options: '옵션',
    size: '크기（px）',
    ecLevel: '오류 정정 레벨',
    fgColor: '전경색',
    bgColor: '배경색',
    downloadPng: 'PNG 다운로드',
    emptyHint: 'QR Code 를 생성할 내용을 입력하세요',
    encNone: '없음',
  },
}
