import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'timestamp',
  route: 'timestamp',
  category: 'convert',
  icon: 'mdi-clock-outline',
  title: {
    'zh-TW': '時間戳轉換',
    en: 'Timestamp Converter',
    ja: 'タイムスタンプ変換',
    ko: '타임스탬프 변환',
  },
  description: {
    'zh-TW': 'Unix 時間戳與日期互轉，顯示即時時間戳與相對時間。',
    en: 'Convert between Unix timestamps and dates, with a live clock and relative time.',
    ja: 'Unix タイムスタンプと日付を相互変換し、現在のタイムスタンプと相対時間を表示します。',
    ko: 'Unix 타임스탬프와 날짜를 상호 변환하고 현재 타임스탬프와 상대 시간을 표시합니다.',
  },
  keywords: ['timestamp', 'unix', 'epoch', 'date', '時間戳', '時間', 'iso', 'utc', 'タイムスタンプ', '타임스탬프'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    nowSeconds: '目前時間戳（秒）',
    nowMillis: '目前時間戳（毫秒）',
    tsToDate: '時間戳 → 日期',
    tsInput: '輸入時間戳（自動判別秒 / 毫秒）',
    detectedSeconds: '判別為：秒',
    detectedMillis: '判別為：毫秒',
    local: '本地時間',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: '相對時間',
    invalidTs: '無效的時間戳',
    dateToTs: '日期 → 時間戳',
    dateInput: '輸入日期 / 時間字串',
    invalidDate: '無法解析日期',
    seconds: '秒',
    millis: '毫秒',
    ago: '前',
    fromNow: '後',
    justNow: '剛剛',
    second: '秒',
    minute: '分鐘',
    hour: '小時',
    day: '天',
    month: '個月',
    year: '年',
  },
  en: {
    nowSeconds: 'Current timestamp (s)',
    nowMillis: 'Current timestamp (ms)',
    tsToDate: 'Timestamp → Date',
    tsInput: 'Enter timestamp (auto-detect s / ms)',
    detectedSeconds: 'Detected: seconds',
    detectedMillis: 'Detected: milliseconds',
    local: 'Local',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: 'Relative',
    invalidTs: 'Invalid timestamp',
    dateToTs: 'Date → Timestamp',
    dateInput: 'Enter a date / datetime string',
    invalidDate: 'Cannot parse date',
    seconds: 's',
    millis: 'ms',
    ago: 'ago',
    fromNow: 'from now',
    justNow: 'just now',
    second: 'second',
    minute: 'minute',
    hour: 'hour',
    day: 'day',
    month: 'month',
    year: 'year',
  },
  ja: {
    nowSeconds: '現在のタイムスタンプ（秒）',
    nowMillis: '現在のタイムスタンプ（ミリ秒）',
    tsToDate: 'タイムスタンプ → 日付',
    tsInput: 'タイムスタンプを入力（秒 / ミリ秒を自動判別）',
    detectedSeconds: '判別結果：秒',
    detectedMillis: '判別結果：ミリ秒',
    local: 'ローカル時間',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: '相対時間',
    invalidTs: '無効なタイムスタンプ',
    dateToTs: '日付 → タイムスタンプ',
    dateInput: '日付 / 日時の文字列を入力',
    invalidDate: '日付を解析できません',
    seconds: '秒',
    millis: 'ミリ秒',
    ago: '前',
    fromNow: '後',
    justNow: 'たった今',
    second: '秒',
    minute: '分',
    hour: '時間',
    day: '日',
    month: 'か月',
    year: '年',
  },
  ko: {
    nowSeconds: '현재 타임스탬프（초）',
    nowMillis: '현재 타임스탬프（밀리초）',
    tsToDate: '타임스탬프 → 날짜',
    tsInput: '타임스탬프 입력（초 / 밀리초 자동 판별）',
    detectedSeconds: '판별 결과: 초',
    detectedMillis: '판별 결과: 밀리초',
    local: '로컬 시간',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: '상대 시간',
    invalidTs: '유효하지 않은 타임스탬프',
    dateToTs: '날짜 → 타임스탬프',
    dateInput: '날짜 / 일시 문자열 입력',
    invalidDate: '날짜를 해석할 수 없습니다',
    seconds: '초',
    millis: '밀리초',
    ago: '전',
    fromNow: '후',
    justNow: '방금',
    second: '초',
    minute: '분',
    hour: '시간',
    day: '일',
    month: '개월',
    year: '년',
  },
}
