import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'timestamp',
  route: 'timestamp',
  category: 'convert',
  icon: 'mdi-clock-outline',
  title: { 'zh-TW': '時間戳轉換', en: 'Timestamp Converter' },
  description: {
    'zh-TW': 'Unix 時間戳與日期互轉，顯示即時時間戳與相對時間。',
    en: 'Convert between Unix timestamps and dates, with a live clock and relative time.',
  },
  keywords: ['timestamp', 'unix', 'epoch', 'date', '時間戳', '時間', 'iso', 'utc'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    nowSeconds: '目前時間戳（秒）',
    nowMillis: '目前時間戳（毫秒）',
    tsToDate: '時間戳 → 日期',
    tsInput: '輸入時間戳（自動判別秒 / 毫秒）',
    detectedSeconds: '判別為：秒',
    detectedMillis: '判別為：毫秒',
    local: '本地時間',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: '相對時間',
    invalidTs: '無效的時間戳',
    dateToTs: '日期 → 時間戳',
    dateInput: '輸入日期 / 時間字串',
    invalidDate: '無法解析日期',
    seconds: '秒',
    millis: '毫秒',
    ago: '前',
    fromNow: '後',
    justNow: '剛剛',
    second: '秒',
    minute: '分鐘',
    hour: '小時',
    day: '天',
    month: '個月',
    year: '年',
  },
  en: {
    nowSeconds: 'Current timestamp (s)',
    nowMillis: 'Current timestamp (ms)',
    tsToDate: 'Timestamp → Date',
    tsInput: 'Enter timestamp (auto-detect s / ms)',
    detectedSeconds: 'Detected: seconds',
    detectedMillis: 'Detected: milliseconds',
    local: 'Local',
    utc: 'UTC',
    iso: 'ISO 8601',
    relative: 'Relative',
    invalidTs: 'Invalid timestamp',
    dateToTs: 'Date → Timestamp',
    dateInput: 'Enter a date / datetime string',
    invalidDate: 'Cannot parse date',
    seconds: 's',
    millis: 'ms',
    ago: 'ago',
    fromNow: 'from now',
    justNow: 'just now',
    second: 'second',
    minute: 'minute',
    hour: 'hour',
    day: 'day',
    month: 'month',
    year: 'year',
  },
}
