import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'qr-scan',
  route: 'qr-scan',
  category: 'media',
  icon: 'mdi-qrcode-scan',
  title: {
    'zh-TW': 'QR Code / 條碼掃描',
    en: 'QR Code / Barcode Scanner',
    ja: 'QR Code / バーコードスキャナー',
    ko: 'QR Code / 바코드 스캐너',
  },
  description: {
    'zh-TW': '用相機即時掃描，或上傳圖片解析 QR Code 與各式條碼。',
    en: 'Scan live with your camera or upload an image to decode QR codes and barcodes.',
    ja: 'カメラでリアルタイムにスキャンするか、画像をアップロードして QR Code やバーコードを読み取ります。',
    ko: '카메라로 실시간 스캔하거나 이미지를 업로드하여 QR Code와 바코드를 해독합니다.',
  },
  keywords: ['qr', 'qrcode', 'barcode', 'scan', '掃描', '條碼', 'zxing', 'スキャン', 'バーコード', '스캔', '바코드'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    camera: '相機掃描',
    image: '圖片解析',
    start: '開始掃描',
    stop: '停止掃描',
    scanning: '掃描中…',
    result: '掃描結果',
    open: '開啟連結',
    uploadHint: '上傳含 QR Code / 條碼的圖片',
    noResult: '尚未掃描到任何內容。',
    errPermission: '無法存取相機，請確認已授權相機權限。',
    errNoCamera: '找不到可用的相機裝置。',
    errDecode: '無法從圖片中解析出條碼。',
  },
  en: {
    camera: 'Camera',
    image: 'Image',
    start: 'Start scan',
    stop: 'Stop scan',
    scanning: 'Scanning…',
    result: 'Scan result',
    open: 'Open link',
    uploadHint: 'Upload an image containing a QR code / barcode',
    noResult: 'Nothing scanned yet.',
    errPermission: 'Cannot access the camera. Please grant camera permission.',
    errNoCamera: 'No camera device available.',
    errDecode: 'Could not decode a barcode from the image.',
  },
  ja: {
    camera: 'カメラスキャン',
    image: '画像から読み取り',
    start: 'スキャン開始',
    stop: 'スキャン停止',
    scanning: 'スキャン中…',
    result: 'スキャン結果',
    open: 'リンクを開く',
    uploadHint: 'QR Code / バーコードを含む画像をアップロード',
    noResult: 'まだ何も読み取っていません。',
    errPermission: 'カメラにアクセスできません。カメラの権限を許可してください。',
    errNoCamera: '利用可能なカメラデバイスが見つかりません。',
    errDecode: '画像からバーコードを読み取れませんでした。',
  },
  ko: {
    camera: '카메라 스캔',
    image: '이미지에서 인식',
    start: '스캔 시작',
    stop: '스캔 중지',
    scanning: '스캔 중…',
    result: '스캔 결과',
    open: '링크 열기',
    uploadHint: 'QR Code / 바코드가 포함된 이미지 업로드',
    noResult: '아직 스캔된 내용이 없습니다.',
    errPermission: '카메라에 접근할 수 없습니다. 카메라 권한을 허용해 주세요.',
    errNoCamera: '사용 가능한 카메라 장치를 찾을 수 없습니다.',
    errDecode: '이미지에서 바코드를 해독할 수 없습니다.',
  },
}
