import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'unit-convert',
  route: 'unit-convert',
  category: 'convert',
  icon: 'mdi-ruler',
  title: {
    'zh-TW': '單位換算',
    en: 'Unit Converter',
    ja: '単位変換',
    ko: '단위 변환',
  },
  description: {
    'zh-TW': '長度、質量、溫度、資料量、面積、體積、速度與時間的單位換算。',
    en: 'Convert length, mass, temperature, data size, area, volume, speed and time.',
    ja: '長さ、質量、温度、データ量、面積、体積、速度、時間の単位を変換します。',
    ko: '길이, 질량, 온도, 데이터 크기, 면적, 부피, 속도, 시간 단위를 변환합니다.',
  },
  keywords: ['unit', 'convert', '單位', '換算', 'length', 'mass', 'temperature', 'speed', '単位変換', '단위 변환'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    category: '類別',
    fromUnit: '從',
    toUnit: '到',
    value: '數值',
    result: '結果',
    catLength: '長度',
    catMass: '質量',
    catTemperature: '溫度',
    catData: '資料量',
    catArea: '面積',
    catVolume: '體積',
    catSpeed: '速度',
    catTime: '時間',
  },
  en: {
    category: 'Category',
    fromUnit: 'From',
    toUnit: 'To',
    value: 'Value',
    result: 'Result',
    catLength: 'Length',
    catMass: 'Mass',
    catTemperature: 'Temperature',
    catData: 'Data size',
    catArea: 'Area',
    catVolume: 'Volume',
    catSpeed: 'Speed',
    catTime: 'Time',
  },
  ja: {
    category: 'カテゴリ',
    fromUnit: '変換元',
    toUnit: '変換先',
    value: '数値',
    result: '結果',
    catLength: '長さ',
    catMass: '質量',
    catTemperature: '温度',
    catData: 'データ量',
    catArea: '面積',
    catVolume: '体積',
    catSpeed: '速度',
    catTime: '時間',
  },
  ko: {
    category: '카테고리',
    fromUnit: '변환 전',
    toUnit: '변환 후',
    value: '값',
    result: '결과',
    catLength: '길이',
    catMass: '질량',
    catTemperature: '온도',
    catData: '데이터 크기',
    catArea: '면적',
    catVolume: '부피',
    catSpeed: '속도',
    catTime: '시간',
  },
}
