import type { ToolMeta, ToolMessages } from '@/types'

export const meta: ToolMeta = {
  id: 'json-format',
  route: 'json-format',
  category: 'text',
  icon: 'mdi-code-json',
  title: {
    'zh-TW': 'JSON 格式化 / 驗證',
    en: 'JSON Format / Validate',
    ja: 'JSON 整形 / 検証',
    ko: 'JSON 포맷 / 검증',
  },
  description: {
    'zh-TW': '格式化、壓縮、排序鍵並即時驗證 JSON。',
    en: 'Format, minify, sort keys and validate JSON live.',
    ja: 'JSON を整形・圧縮し、キーを並べ替えてリアルタイムに検証します。',
    ko: 'JSON을 포맷, 압축, 키 정렬하고 실시간으로 검증합니다.',
  },
  keywords: ['json', 'format', 'minify', 'validate', 'pretty', '格式化', '壓縮', '驗證', '整形', '検証', '포맷', '검증'],
}

export const messages: ToolMessages = {
  'zh-TW': {
    inputJson: '輸入 JSON',
    format: '格式化',
    minify: '壓縮',
    sortKeys: '排序鍵',
    indent: '縮排',
    indent2: '2 空格',
    indent4: '4 空格',
    indentTab: 'Tab',
    valid: 'JSON 有效',
    parseError: '解析錯誤：{msg}',
    download: '下載 .json',
  },
  en: {
    inputJson: 'Input JSON',
    format: 'Format',
    minify: 'Minify',
    sortKeys: 'Sort keys',
    indent: 'Indent',
    indent2: '2 spaces',
    indent4: '4 spaces',
    indentTab: 'Tab',
    valid: 'Valid JSON',
    parseError: 'Parse error: {msg}',
    download: 'Download .json',
  },
  ja: {
    inputJson: 'JSON を入力',
    format: '整形',
    minify: '圧縮',
    sortKeys: 'キーを並べ替え',
    indent: 'インデント',
    indent2: 'スペース 2 個',
    indent4: 'スペース 4 個',
    indentTab: 'タブ',
    valid: 'JSON は有効です',
    parseError: '解析エラー：{msg}',
    download: '.json をダウンロード',
  },
  ko: {
    inputJson: 'JSON 입력',
    format: '포맷',
    minify: '압축',
    sortKeys: '키 정렬',
    indent: '들여쓰기',
    indent2: '공백 2칸',
    indent4: '공백 4칸',
    indentTab: '탭',
    valid: '유효한 JSON',
    parseError: '파싱 오류: {msg}',
    download: '.json 다운로드',
  },
}
